### ISSUE TITLE
Extract secrets in collections

### ISSUE THREAD

**Issue by Ndpnt** [OpenTermsArchive/deployment#12]
Currently, secrets are stored in this file https://github.com/OpenTermsArchive/deployment/blob/main/roles/engine/files/.env.
All collections share the same secrets, and it is not possible to reuse these recipes as is. Therefore, these secrets must be extracted and defined in each collection.

**Comment by MattiSG** [comment]
Implemented in https://github.com/OpenTermsArchive/deployment/pull/30.
