### ISSUE TITLE
Deployment does not work when changing declarations folder

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/deployment#8]
I had a hard time deploying the latest version of the engine on contrib because the pm2 process was executing in `/home/debian/ota` which was the original folder the process have been launched in.

As deployment only stops the process and restarts it after update, the process did not start as it was being executed from there.

I had to manually `pm2 remove ota` in order for the deployment to work correctly.

**Comment by MattiSG** [comment]
Implemented in https://github.com/OpenTermsArchive/deployment/pull/46.
